### ISSUE TITLE
Clean up routes

### ISSUE THREAD

**Issue by quinnleong** [zjernst/soundscape#3]
You'll probably want to:
- get all tracks for a given environment at /environments/:id (include the associated tracks when you pull the environment data)
- add or delete a tag on a track within track edit; the many-layers-nested routes can get pretty messy (the example in the sample proposal is nested that way because there's live tag-adding and -deleting... it's simpler to add the tags in the track new/edit form unless you strongly prefer that functionality)

**Comment by zjernst** [comment]
Thanks for the feedback! I cleaned the routes up some (moved tags to part of track form rather than its own thing). Routes are probably the concept I'm still iffiest with, so if anything still seems off let me know.
