### ISSUE TITLE
Make non-mvp components bonus

### ISSUE THREAD

**Issue by quinnleong** [zjernst/soundscape#4]
My suggestion would be making any non-mvp components (e.g. recent activity index, additional info index, welcome index, etc.) bonus. You have quite a few components, and they often take longer than expected! This way you can still make them if there is time, but they're not essential.

**Comment by zjernst** [comment]
Totally agree. Moved all my lovely site-building-aspirations to the bonus to hopefully be worked on after the foundation is implemented.
